import Page from "./BasePage"
export default class CommonElements {
    get elements() {
        return {
            common_page_header: ".page-header-text",
            common_help_icon: ".aamc-i-help-o",
            common_history: ".page-header-link [title = 'History']",
            common_sub_header: ".setup-mat-card-title",
            common_page_button: (bttn_name) => { return `button[title='${bttn_name}']` },
            common_edit_button: "button[title='Edit']",
            common_label: (str) => { return `//div[@class='label'][contains(.,'${str}')]` },
            common_page: "//*[contains(@class,'cdk-overlay-container')]",
            common_page_toast: "//*[contains(@class,'toast-message')]",
            common_profile_icon: " .user .mini-account",
            common_account_dropdown_links: ".account-dropdown-link",
            common_account_dropdown_link: (str) => { return `//*[text()='${str}']` },
            common_header_user_details: ".user-details div",
            common_miniaccount_circletext: ".mini-account .circle-text",
            common_myaccount_returntoapp: "//a[@id='returnToApp']",
            desc_hover_text: "aamc-ui-tool-tip div.tooltip-conatiner",
            leftNavModule: (module) => { return `//aamc-ui-vertical-nav-item/a[contains(text(),'${module}')]` },
            common_cancel: "button[title='Cancel']",
            common_close: "i.aamc-i-close",
            common_popup_option_button: (button) => { return `button[title='${button}']` },
            common_section_header: (sectionHeader) => { return `//mat-card-content//h3[text()='${sectionHeader}']` },
            common_button_by_title: (title) => { return `//button[normalize-space(@title)="${title}"]` },
            common_button: (str) => { return `//button/span[contains(text(),'${str}')]` },
            common_element_by_Text: (text) => { return `//*[contains(text(),"${text}")]` },
            checkbox_common: (str) => { return `//span[contains(text(),"${str}")]/ancestor::mat-checkbox/label ` },
            common_button_by_label: (bttn_name) => { return `//*[@aria-label="${bttn_name}"]` },
            popup_modal_title: "aamc-ui-modal .aamc-modal-title-text",
            common_input_text: (input_name) => { return `input#${input_name}` },
            common_error_msg: (input_id) => { return `mat-error#${input_id}` },
            common_no_containt_display: "aamc-ui-no-results .toolbar-row-no-results",
            common_startDate_picker: "#startDate",
            common_endDate_picker: "#endDate",
            checkboxes: "table tbody tr .mat-checkbox",
            sort_icon: (str) => { return `//*[contains(@class,'mat-header-row')]//*[contains(text(),'${str}')]//..//..//*[contains(@class,'mat-sort-header-arrow')]` },
            In_column_date_error: (formname) => { return `aamc-ui-extended-field[fieldformcontrol='${formname}'] mat-error ` },
            applicant_tabs: (header) => { return `//*[@class="mat-tab-label-content"][text()="${header}"]` },
            leftNavigationPanel: "e4p-dashboard-container aamc-ui-vertical-nav",
            ErrorMessage: (str) => { return `#${str}.mat-error` },
            popup_modal: ".cdk-overlay-pane .mat-dialog-container",
            validation: (str) => { return `//p[contains(text(),'${str}')]` },
            modal_button: (str) => { return `//span[contains(text(),'${str}')]` },
            loader_icon: ".loader-container",
            filters_save_button: (title) => { return `button[title='${title}']` },
            subHeaderInterview: ".mat-mdc-card-header .mat-mdc-card-title",
            interviewerToggleText: "#interviewer-toggle-text",
            main_data_filters_field_set: ".main-filter-section .main-filter-field-set",
            main_data_filters_show_hide: ".main-filter-field > span > i",
            desc_hover_text: "aamc-ui-tool-tip div.tooltip-conatiner",
            popup_modal1: ".mat-dialog-container",
            modal_close_icon: "mat-dialog-container .close-button",
            modal_cancel_button: " mat-dialog-container [title='Cancel']",
            filter_criteria_radio_buttons: ".filter-criteria-list .mat-radio-button",
            ISPS_name: "a.season-program-info span",
            epm_Season_Link: '//*[@class="info-link-tooltip tooltip ng-star-inserted"]//span[contains(text(),"202")]',
            epm_Instituion_Link: '//*[@class="season-program-info ng-star-inserted"][1]',
            epm_Specialty_Link: '//*[@class="season-program-info ng-star-inserted"][2]',
            epm_separator_line: '//*[@class="navigations-element-separator"]',
            updated_value: (str) => { return `//*[@class='value'][contains(text(),'${str}')]` },
            element_by_Text: (text) => { return `//*[text()="${text}"]` },
            pdws_Institution_Link: '(//*[@class="program-navigation"]//a/span)[1]',
            pdws_Specialty_Link: '(//*[@class="program-navigation"]//a/span)[2]',
            common_toast_message: "//aamc-toast//*[contains(@class,'toast-message')]",
            updated_value_prog_req: (str) => { return `//*[@class='value']//p[contains(text(),'${str}')]` },
            Card_Notification_Text: ".card-notification-margin p",
            rpeUser_SignOut: "//span[text()='Sign out']",
            rpeUser_AccountClick: "//div[@class='mini-account']"
        }
    }
}

const common_elements = new CommonElements();
exports.CommonElements = common_elements.elements;